### ISSUE TITLE
Force deriving strategies in style guide

### ISSUE THREAD

**Issue by vrom911** [kowainik/org#32]
- [ ] Add `DerivingStrategies` to the list of allowed extensions by default?
- [ ] Update all code examples to specify strategies

**Comment by chshersh** [comment]
Since GHC-8.8 we can use `-Wmissing-deriving-strategies` flag to get warnings when we are not using deriving strategies!

* https://ghc.gitlab.haskell.org/ghc/doc/users_guide/using-warnings.html#ghc-flag--Wmissing-deriving-strategies

I guess we should also add to the list of flags enabled by default :slightly_smiling_face:
